# 赛前培训2

python有着大量功能强大的第三方库。这些第三方库可以大大扩充Python的功能，我们在实际使用中往往也离不开这些第三方库。

Numpy是Python的一种开源的数值计算扩展。这种工具可以用来存储和处理大型矩阵，比Python自身的嵌套列表（nested list structure）结构要高效的多。Numpy（Numeric Python）提供了许多高级的数值编程工具。Numpy的一个重要特性是它的数组计算，是我们做数据分析必不可缺少的一个包。

导入Python库使用关键字import,后面可以自定义库的简称，但是一般都将Numpy命名为np，pandas命名为pd。

使用前一定要先导入Numpy包，导入的方法有以下几种：

In [9]:
import numpy as np

In [10]:
import pandas as pd

In [15]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [14]:
a=[1,2,3,4]
a

[1, 2, 3, 4]

# 1.Numpy的数组对象及其索引

## 数组上的数学操作

假如我们想将列表中的每个元素增加1，但列表不支持这样的操作

In [16]:
a=[1,2,3,4]
b=[4,5,6,7]

In [17]:
a+b

[1, 2, 3, 4, 4, 5, 6, 7]

In [18]:
a+1

TypeError: can only concatenate list (not "int") to list

In [19]:
[x+1 for x in a]

[2, 3, 4, 5]

In [20]:
[x+y for (x,y) in zip(a,b)]

[5, 7, 9, 11]

与另一个数组相加，得到对应元素相加的结果：

### 这样的操作比较麻烦，而且在数据量特别大的时候会非常消耗时间

### 如果我们使用Numpy，就会变得特别简单

### 产生数组

In [22]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

从列表产生数组：

In [23]:
L=[1,2,3,4]
L

[1, 2, 3, 4]

In [26]:
b=np.array(L)
b

array([1, 2, 3, 4])

从列表传入：

In [27]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [28]:
L

[1, 2, 3, 4]

In [29]:
a

array([1, 2, 3, 4])

In [30]:
a+L

array([2, 4, 6, 8])

生成全0数组：

In [34]:
a=np.zeros(5,dtype=int)
a

array([0, 0, 0, 0, 0])

生成全1的数组：

In [37]:
a=np.ones(20,dtype=int)
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

可以使用fill方法将数组设为指定值：

In [46]:
a.fill(3.9)
a

array([3.9, 3.9, 3.9, 3.9, 3.9, 3.9, 3.9, 3.9, 3.9, 3.9, 3.9, 3.9, 3.9,
       3.9, 3.9, 3.9, 3.9, 3.9, 3.9, 3.9])

In [45]:
a=a.astype('float')
a

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3.])

与列表不同，数组中要求所有元素的dtype是一样的，如果传入参数的类型与数组类型不一样，需要按照已有的类型进行转换。

还可以使用一些特定的方法生成特殊的数组

生成整数序列：

In [53]:
a=np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

np.arange(初始值，终点（最后一位数为终点数-1），步长)

生成等差数列：

In [56]:
a=np.linspace(1,10,10)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

生成随机数：

In [58]:
np.random.rand(10)

array([0.57358665, 0.64824399, 0.22583977, 0.97975286, 0.24058563,
       0.11169566, 0.7376019 , 0.87281991, 0.13258722, 0.20441039])

In [59]:
np.random.randn(10)

array([ 0.55582258,  1.90141706, -0.35661079, -0.19541207,  0.57253623,
        0.50621764,  0.59052631,  0.03688875, -0.31698728,  1.13774332])

In [60]:
np.random.randint(1,10,5)

array([2, 2, 4, 3, 1])

## 数组属性

查看类型：

In [66]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [62]:
type(a)

numpy.ndarray

In [65]:
a.shape

(2, 4)

In [67]:
a.size

8

In [68]:
a.ndim

2

查看数组中的数据类型：

查看形状，会返回一个元组，每个元素代表这一维的元素数目：

或者使用：

In [70]:
np.shape(a)

(2, 4)

查看数组里面的元素的数目：

In [71]:
a.size

8

查看数组的维度：

In [72]:
a.ndim

2

## 索引与切片 

和列表相似，数组也支持索引和切片操作。

In [73]:
a=[1,2,3,4]
a

[1, 2, 3, 4]

In [74]:
a[0]

1

In [75]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [76]:
a[0]

1

索引第一个元素：

修改第一个元素的值：

In [78]:
a[0]=2
a

array([2, 2, 3, 4])

切片，支持负索引：

In [79]:
a[1:3]

array([2, 3])

In [80]:
a[1:-1]

array([2, 3])

省略参数：

In [81]:
a[1:]

array([2, 3, 4])

In [82]:
a[:]

array([2, 2, 3, 4])

假如我们记录数学建模校赛的报名人数：

In [83]:
a=np.array([23,34,44,56,67])
a

array([23, 34, 44, 56, 67])

计算每天报名人数：

[34,44,56,67]
[23,34,44,56]

In [84]:
b=a[1:]-a[:4]
b

array([11, 10, 12, 11])

## 多维数组及其属性 

array还可以用来生成多维数组

In [85]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

事实上我们传入的是一个以列表为元素的列表，最终得到一个二维数组。

查看形状：

In [86]:
a.shape

(2, 4)

查看总的元素个数：

In [87]:
a.size

8

查看维数：

In [88]:
a.ndim

2

## 多维数组的索引 

对于二维数组，可以传入两个数字来索引：

In [89]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [90]:
a[1,3]

8

其中，1是行索引，3是列索引，中间用逗号隔开，事实上，python会将它们看成一个元组(1,3),然后按照顺序进行对应。

可以利用索引给它赋值：

In [92]:
a[1,3]=2
a

array([[1, 2, 3, 4],
       [5, 6, 7, 2]])

事实上，我们还可以使用单个索引来索引一整行内容：

In [93]:
a[1]

array([5, 6, 7, 2])

Python会将这单个元组当成对第一维的索引，然后返回对应的内容。

In [96]:
a[1,:]

array([5, 6, 7, 2])

## 多维数组切片 

多维数组，也支持切片操作：

In [98]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

想得到第一行的第4和第5两个元素：

In [99]:
a[0,3:5]

array([4, 5])

得到最后两行的最后两列：

In [102]:
a[-2:,3:]

array([[ 9, 10],
       [14, 15]])

得到第三列：

In [101]:
a[:,2]

array([ 3,  8, 13])

每一维都支持切片的规则，包括负索引，省略：

例如，取出1，3行的奇数列

In [104]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [103]:
a[::2,::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## 切片的引用 

切片在内存中使用的是引用机制。

In [106]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [107]:
b=a[1:3]
b

array([2, 3])

In [109]:
b[0]=10
b

array([10,  3])

In [110]:
a

array([ 1, 10,  3,  4])

切片机制意味着，Python并没有为b分配新的空间来存储它的值，而是让b指向了a所分配的内存空间，因此，改变b会改变a的值：

这种现象在列表中不会出现：

In [113]:
a=[1,2,3,4]
b=a[1:3]
b[0]=10
b

[10, 3]

In [114]:
a

[1, 2, 3, 4]

这样做的好处在于，对于很大的数组，不用大量复制多余的值，节约了空间。

缺点在于，可能出现改变一个值而使另一个值改变的情况。

一个解决方法是使用copy()方法产生一个赋值，这个复制会申请新的内存：

In [115]:
a=np.array([1,2,3,4])
b=a[1:3].copy()
b[0]=10
a

array([1, 2, 3, 4])

## 花式索引 

切片只能支持连续或者等间隔的切片操作，要想实现任意位置的操作，需要使用花式索引。

## 一维花式索引 

与range函数类似，我们可以使用arange函数来产生等差数组。

In [117]:
a=np.arange(0,101,10)
a

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

花式索引需要指定索引位置：

In [120]:
b=[2,3,-2]
y=a[b]
y

array([20, 30, 90])

还可以使用布尔数组来花式索引：

In [121]:
b=np.array([0,1,0,1,0,0,0,0,1,1,1],dtype=bool)
b

array([False,  True, False,  True, False, False, False, False,  True,
        True,  True])

In [122]:
a[b]

array([ 10,  30,  80,  90, 100])

b必须是布尔数字。长度必须和数组长度相等。

## 二维花式索引 

In [123]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

对于二维花式索引，我们需要给定行和列的值：

返回的是一条次对角线上的3个值。

In [124]:
a[(0,1,2),(1,2,3)]

array([ 2,  7, 12])

返回的是最后三行的第1，3列。

In [126]:
a[1:,::2]

array([[ 5,  7],
       [ 9, 11],
       [13, 15]])

也可以使用mask进行索引：

In [129]:
b=np.array([0,1,0,1],dtype=bool)
b
a[b]

array([[ 5,  6,  7,  8],
       [13, 14, 15, 16]])

与切片不同，花式索引返回的是原对象的一个复制而不是引用。

## "不完全"索引 

只给定行索引的时候，返回整行。

In [130]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [132]:
y=a[:3]
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

这时候也可以使用花式索引取出第2,3行：

In [133]:
x=np.array([0,1,1,0],dtype=bool)
a[x]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## where语句 

where函数会返回所有非零元素的索引

## 一维数组 

先看一维的例子：

In [134]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [135]:
a>2

array([False, False,  True,  True])

判断数组中的元素是不是大于2：

In [136]:
a>2

array([False, False,  True,  True])

数组中所有大于2的元素的索引位置：

In [137]:
np.where(a>2)

(array([2, 3], dtype=int64),)

注意到where的返回值是一个元组。返回的是索引位置。

也可以直接用数组操作。

In [138]:
a[np.where(a>2)]

array([3, 4])

# 2.数组类型 

## 类型转换 

## asarray转换 

In [142]:
a

array([1, 2, 3, 4])

In [147]:
a=np.asarray(a,dtype=float)
a

array([1., 2., 3., 4.])

## astype转换 

In [151]:
b=a.astype(int)

In [152]:
b

array([1, 2, 3, 4])

# 3.数组操作 

## 以协会为例 

In [154]:
##协会
assoc_name=['数学建模','数据分析','理论研究','carefree','灯谜','魔术','RC模型','软件工程','散打','跆拳道']

In [155]:
##人数
assoc_num=np.array([145,53,34,46,156,125,76,65,33,43])

In [156]:
##星级
assoc_star=np.array([3,3,3,4,4,4,3,3,3,3])

## 数组排序 

#### sort函数 

In [157]:
np.sort(assoc_num)

array([ 33,  34,  43,  46,  53,  65,  76, 125, 145, 156])

#### argsort函数 

In [159]:
a=np.argsort(assoc_num)
a

array([8, 2, 9, 3, 1, 7, 6, 5, 0, 4], dtype=int64)

argsort返回从小到大的排列在数组中的索引位置：

In [160]:
assoc_name[a[0]]

'散打'

## 求和 

In [161]:
sum(assoc_num)

776

In [162]:
np.sum(assoc_num)

776

#### 最大值

In [163]:
np.max(assoc_num)

156

#### 最小值

In [164]:
np.min(assoc_num)

33

#### 均值

In [165]:
np.mean(assoc_num)

77.6

#### 标准差

In [166]:
np.std(assoc_num)

44.484154482242324

### 相关系数矩阵

In [167]:
np.cov(assoc_num,assoc_star)

array([[2.19871111e+03, 1.04666667e+01],
       [1.04666667e+01, 2.33333333e-01]])

## 多维数组操作 

### 数组形状

In [172]:
a=np.array([1,2,3,4,5,6,7,8])

In [171]:
a.shape=2,4
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

与之对应的方法是reshape，但它不会修改原来数组的值，而是返回一个新的数组：

In [175]:
b=a.reshape(2,4)

In [176]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [174]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

### 转置

In [180]:
b.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### 数组连接 

有时我们需要将不同的数组按照一定的顺序连接起来：

In [182]:
a=np.array([[1,2,3,4],[5,6,7,8]])
b=np.array([[9,10,11,12],[13,14,15,16]])

concatenate((a0,a1,...,aN),axis=0)

注意，这些数组要用（）包括到一个元组中去。

除了给定的轴外，这些数组其他轴的长度必须是一样的。

默认沿着第一维进行连接：

In [183]:
np.concatenate((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

沿着第二维进行连接：

In [184]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

注意到这里x和y的形状是一样的，还可以将它们连接成三维的数组，但是concatenate不能提供这样的功能：

In [185]:
z=np.array((a,b))
z

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

###### Numpy提供了分别对应三种情况的函数：vstack,hstack,dstack 

In [187]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [188]:
b

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [186]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [189]:
np.hstack((a,b))

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [190]:
np.dstack((a,b))

array([[[ 1,  9],
        [ 2, 10],
        [ 3, 11],
        [ 4, 12]],

       [[ 5, 13],
        [ 6, 14],
        [ 7, 15],
        [ 8, 16]]])

## numpy内置函数

https://blog.csdn.net/honest_boy/article/details/86542098